name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  ts-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        run: yarn install --frozen-lockfile

      - name: yarn test
        run: yarn test
