name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  ts-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: pnpm install
        run: pnpm install --frozen-lockfile

      - name: pnpm test
        run: pnpm test
